### ISSUE TITLE
WebSocketでの謎のエラー

### ISSUE THREAD

**Issue by ZOI-dayo** [ZOI-dayo/AtCoder_Discord_Bot#1]
```text
error: Uncaught (in promise) InvalidStateError: readyState not OPEN
      shard.socket?.send(
                    ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:324:13)
    at https://deno.land/x/discordeno@18.0.1/gateway/shard/startHeartbeating.ts:52:21
    at Object.action (ext:deno_web/02_timers.js:149:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:66:10)
    at eventLoopTick (ext:core/01_core.js:187:21)
```

**Comment by ZOI-dayo** [comment]
再発
```text
...
AJLのレート変動がないか確認中...
AJLのレート変動はありませんでした。
AJLのレート変動はありませんでした。
CLOSING EXISTING SHARD: #0
error: Uncaught InvalidStateError: readyState not OPEN
    shard.socket?.send(JSON.stringify({
                  ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:324:13)
    at https://deno.land/x/discordeno@18.0.1/gateway/shard/startHeartbeating.ts:22:19
    at Object.action (ext:deno_web/02_timers.js:149:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:66:10)
    at eventLoopTick (ext:core/01_core.js:187:21)
```

**Comment by ZOI-dayo** [comment]
```
$ wc log/2023-06-25-03-42-38.log
  21094   21258 1050680 log/2023-06-25-03-42-38.log
```
より21094行

ほとんどが、10分間隔の
```
AJLのレート変動がないか確認中...
AJLのレート変動はありませんでした。
AJLのレート変動はありませんでした。
```
より、70,313.33分後、すなわち7週間...え? 未来...?

**Comment by ZOI-dayo** [comment]
```
$ grep -c "AJLのレート変動がないか確認中..." log/2023-06-25-03-42-38.log
6978
```
ということは69780m、いや変わらんな、あれ、、、、多重起動してる?

**Comment by ZOI-dayo** [comment]
いや違う、1分ごとなので、6/30の12時ちょうどくらいだ
ただこの鯖はUTC時間っぽいので、日本時間6/30 3:00

**Comment by ZOI-dayo** [comment]
その時間は障害なさそう、時刻が12:00ちょうどっぽいのでなんかある?

**Comment by ZOI-dayo** [comment]
> ```
> error: Uncaught (in promise) InvalidStateError: readyState not OPEN
>       shard.socket?.send(
>                     ^
>     at WebSocket.send (ext:deno_websocket/01_websocket.js:324:13)
>     at https://deno.land/x/discordeno@18.0.1/gateway/shard/startHeartbeating.ts:52:21
>     at Object.action (ext:deno_web/02_timers.js:149:11)
>     at handleTimerMacrotask (ext:deno_web/02_timers.js:66:10)
>     at eventLoopTick (ext:core/01_core.js:187:21)
> ```

これは2023-06-10-15-53-26.logであるので、
```
$ grep -c "AJLのレート変動がないか確認中..." log/2023-06-10-15-53-26.log
6264
```

6/15 12:17:26 (UTC)となる、やっぱりお昼くらい? うーん??

**Comment by ZOI-dayo** [comment]
https://github.com/discordeno/discordeno/issues/2685
> fixed in v19

更新しないと、だね

**Comment by ZOI-dayo** [comment]
まだ19は来てないのか、待とう
