### ISSUE TITLE
discordenoの認証エラー?

### ISSUE THREAD

**Issue by ZOI-dayo** [ZOI-dayo/AtCoder_Discord_Bot#3]
```
新規コンテストがないか確認中...
error: Uncaught (in promise) Error: [403] The Authorization token you passed did not have permission to the resource.
{"message":"Missing Access","code":50001}
  Error.captureStackTrace(errorStack);
        ^
    at Object.runMethod (https://deno.land/x/discordeno@18.0.1/rest/runMethod.ts:30:9)
    at getChannel (https://deno.land/x/discordeno@18.0.1/helpers/channels/getChannel.ts:19:33)
    at Object.converted.<computed> [as getChannel] (https://deno.land/x/discordeno@18.0.1/bot.ts:402:7)
    at file:///home/zoi/projects/atcoder-discord-bot/src/functions/notify_contest.ts:24:43
    at file:///home/zoi/projects/atcoder-discord-bot/src/functions/notify_contest.ts:31:7
    at Array.forEach (<anonymous>)
    at file:///home/zoi/projects/atcoder-discord-bot/src/functions/notify_contest.ts:22:12
    at Array.forEach (<anonymous>)
    at checkNewContest (file:///home/zoi/projects/atcoder-discord-bot/src/functions/notify_contest.ts:21:12)
    at eventLoopTick (ext:core/01_core.js:181:11)
```

**Comment by ZOI-dayo** [comment]
一瞬で死んでた
```
error: Uncaught (in promise) Error: [403] The Authorization token you passed did not have permission to the resource.
{"message":"Missing Access","code":50001}
  Error.captureStackTrace(errorStack);
        ^
    at Object.runMethod (https://deno.land/x/discordeno@18.0.1/rest/runMethod.ts:30:9)
    at getChannel (https://deno.land/x/discordeno@18.0.1/helpers/channels/getChannel.ts:19:33)
    at Object.converted.<computed> [as getChannel] (https://deno.land/x/discordeno@18.0.1/bot.ts:402:7)
    at file:///home/zoi/projects/atcoder-discord-bot/src/functions/ajl_notify.ts:23:41
    at eventLoopTick (ext:core/01_core.js:181:11)
```

**Comment by ZOI-dayo** [comment]
パーミッション3072でやってみる

**Comment by ZOI-dayo** [comment]
まただな、`abc312のレート変動がないか確認中...`x4のあとに発生してる
