### ISSUE TITLE
レート変動通知エラー

### ISSUE THREAD

**Issue by ZOI-dayo** [ZOI-dayo/AtCoder_Discord_Bot#4]
```
abc309のレート変動がないか確認中...
error: Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
  return await (await fetch(`https://atcoder.jp/contests/${contest}/results/json`)).json() as ContestResult[];
         ^
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:368:14)
    at consumeBody (ext:deno_fetch/22_body.js:245:12)
    at eventLoopTick (ext:core/01_core.js:181:11)
    at async Module.getContestResult (file:///home/zoi/projects/atcoder-discord-bot/src/atcoder.ts:162:10)
    at async sendMessage (file:///home/zoi/projects/atcoder-discord-bot/src/functions/rate_change.ts:10:28)
```

**Comment by ZOI-dayo** [comment]
リクエスト送り過ぎでTooManyRequestされてるのでは?
